### PR TITLE
Sorting - don't treat 0 as negative infinity

### PR DESCRIPTION
**Pull request by benmccann**
Fixes https://github.com/DataTables/DataTablesSrc/issues/114

### CODE REVIEW

**Comment by DataTables** [comment]
Looks good to me - thanks for the PR! Are you happy for this to be included under the MIT license?

**Comment by benmccann** [comment]
Yes

**Comment by DataTables** [comment]
Awesome - thanks :)

**Comment by benmccann** [comment]
No problem. Any idea when there might be a 1.10.17 release with the latest fixes and improvements?

**Comment by DataTables** [comment]
Currently expecting it to be February - although not much more sure than that!

**Pull request merged**
