### PR TITLE
Fix `js/integration/dataTables.bootstrap5.js`

### PR DESCRIPTION
**Pull request by WinterSilence**
Keep `ul.pagination` attributes added by events (for example `initComplete`)

### CODE REVIEW

**Comment by AllanJard** [comment]
Looks good - thank you. Are you happy for that to be included under the MIT license?

**Comment by WinterSilence** [comment]
@AllanJard
> Are you happy for that to be included under the MIT license?

what you mean?

**Comment by AllanJard** [comment]
You've written some code - I'm just checking that you are happy for it to be released under the license we use - the MIT open source license.

**Comment by WinterSilence** [comment]
@AllanJard sure, otherwise I would not sended PR to this repo

**Comment by AllanJard** [comment]
Yeah - see redundant, but its just for confirmation rather than needing to set up a Contributor License Agreement.

**Pull request merged**
