### PR TITLE
update MIT license url

### PR DESCRIPTION
**Pull request by salim114**
## proposed changes

update MIT license url and create index for Non-jQuery initialisation example

### CODE REVIEW

**Comment by salim114** [comment]
## proposed changes

create index for Non-jQuery initialisation example

**Comment by AllanJard** [comment]
Many thanks for this! Are you happy for your index listing to be included under the MIT license?

**Comment by salim114** [comment]
HI Allan, first of all many many thanks for the amazing DataTables, second thing i wanted to pull two requests, one to change the correct url to the MIT licence when we click on it, and the other PR is to create index for Non-jQuery initialisation example beside the other indexes page examples. in fact i did put it under "update MIT license url" by mistake other wise index page of Non-jQuery initialisation is a independent PR 
Best regards.

**Comment by AllanJard** [comment]
No worries - I'm happy with it like this. It is two septate commits, so all good.

Thank you for your kind words :)

**Pull request merged**
