### PR TITLE
rows([ids], {search: 'removed'}) optimization

### PR DESCRIPTION
**Pull request by dagadbm**
This is an optimisation that is very noticeable when using the rows([ids], {search: 'removed'}) in particular when the data table has a LOT of rows (like 50k+).

For more about this discussion check this [issue](https://github.com/DataTables/DataTablesSrc/issues/118).

### CODE REVIEW

**Comment by DataTables** [comment]
Awesome - thanks for this. It looks good to me.

One thing I would like to see changed is the first `if` and `if else` condition - they result in the same action so could be combined. I'm happy to make that change after pulling this in, or to take an updated PR?

Are you happy for this to be included under the MIT license?

**Comment by dagadbm** [comment]
yes I have no problem with the licenses etc.

I'm not sure I understood what you meant by the if one is displayMaster slice other is displayFiltered slice so I will just let you do it . 

Also, I didn't do the "removed search" for the below else if (index/original) (I just noticed it) but I am not comfortable changing that because I don't really know how to test that case and I don't wanna break stuff.

**Comment by DataTables** [comment]
I've moved the code around a little for that change and also to match the code styling of the rest of DataTables for consistency in 64b3e958bc86f3b2820e3a92e988c4463eb086e3.

I agree, something similar could be done for the index order. We are currently revamping the unit tests, and I'll make sure that this all gets covered in them.

**Comment by dagadbm** [comment]
let me know if I can help in anything else :)

**Pull request merged**
