### PR TITLE
The change discussed in #653

### PR DESCRIPTION
**Pull request by strang91**
Moved from https://github.com/DataTables/DataTables/pull/664

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this - are you happy for this to be included under the MIT license?

I don't have a coding standard document published, but I do always require braces be used. I can change the `continue` (I would actually prefer it to be negated so there is no continue actually) or if you would, that would be great.

**Comment by strang91** [comment]
MIT License is good for me.

No problem, Just tell me what you wish to be changed & I'll change it...

**Comment by DataTables** [comment]
The logic for the `continue` could be inverted, so rather than having a continue, just check for the cells before using them. I'll try running it, probably on Monday and run unit tests on it and hopefully commit it in then.

**Comment by strang91** [comment]
Replaced the continue with an if condition.

**Comment by DataTables** [comment]
I'm afraid I've not had a chance to look into this yet - but I've not forgotten. I will do asap.

**Comment by strang91** [comment]
Hi. Have you had a chance to look into this? Is there a chance that this patch will make it into the next release?

Thanks again.

**Comment by DataTables** [comment]
I plan to review it this coming week :-)

**Comment by DataTables** [comment]
Merged in now - thanks for your input with this - hugely appreciated! It will be in 1.10.10 which will be released later this week or next.

**Comment by strang91** [comment]
Thanks

**Pull request merged**
